# Generated by Django 4.2.4 on 2023-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=100)),
                ('D_age', models.IntegerField()),
                ('D_blood', models.TextField()),
            ],
        ),
    ]
