# Generated by Django 4.2.4 on 2023-10-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='D_city',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donors',
            name='D_email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donors',
            name='D_phone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
